services:
  - type: web
    name: cysterciannum
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: free 